### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by GroovyDrifter** [HatScripts/youtube-auto-liker#18]
I use it on Tampermonkey 4.16.1 over Chrome 105.0.5195.125 running macos Monterey 12.6. Videos run to the end and no auto liking is done.

**Comment by NoahBK** [comment]
Same boat here. 4.16.1 Tampermonkey. Brave on version 105.0.5195.127.

**Comment by HatScripts** [comment]
Thanks for letting me know. This issue should now be fixed: https://github.com/HatScripts/youtube-auto-liker/commit/f32c224384bf5a8f72e5987f55d5a81cc7e9519d

**Comment by kas-cor** [comment]
@version        1.3.9

YouTube Auto-Liker:  Checking whether subscribed...
YouTube Auto-Liker:  We are subscribed
YouTube Auto-Liker:  Trying to like video...
YouTube Auto-Liker:  Failed to like video: Error: Couldn't find like button. Will try again in 5000 ms...
YouTube Auto-Liker:  Checking whether subscribed...
YouTube Auto-Liker:  We are subscribed
YouTube Auto-Liker:  Trying to like video...
Failed to like video: Error: Couldn't find like button. Will try again in 5000 ms...

**Comment by HatScripts** [comment]
@kas-cor Should now be working with old and new YouTube like button. v1.3.10 - https://github.com/HatScripts/youtube-auto-liker/commit/6adfb000b0d8f2b9e5451afd04fa56bb6027d685

**Comment by GroovyDrifter** [comment]
> @Version 1.3.9
> 
> YouTube Auto-Liker: Checking whether subscribed... YouTube Auto-Liker: We are subscribed YouTube Auto-Liker: Trying to like video... YouTube Auto-Liker: Failed to like video: Error: Couldn't find like button. Will try again in 5000 ms... YouTube Auto-Liker: Checking whether subscribed... YouTube Auto-Liker: We are subscribed YouTube Auto-Liker: Trying to like video... Failed to like video: Error: Couldn't find like button. Will try again in 5000 ms...

Can I activate somehow this output in tampermonkey to check why it is still not working for me? I'm checking it at work with a completely different setup than in home.

**Comment by NoahBK** [comment]
I am still having issues with it. It is not liking the video regardless of me being subscribed or not. And regardless of me changing the watch time duration or not.

**Comment by 29039** [comment]
I reinstalled it but still not working

**Comment by HatScripts** [comment]
The issue seems to be that the debugger had stopped working and was throwing an exception. I've updated the code and it should be working now.

v1.3.11 - https://github.com/HatScripts/youtube-auto-liker/commit/1efb17d8951d3f5a0d5ad50502a4ee9bc33ba05d

**Comment by GroovyDrifter** [comment]
Weird enough, it looks like it works but it does not, it actually likes the video but then next time it checks it is not liked. May youtube be checking something when the like button is clicked to avoid this to work?

`YouTube Auto-Liker:  Checking whether subscribed...
Liker:  We are subscribed
Liker:  Trying to like video...
Liker:  Found like button
Liker:  It's unclicked. Clicking it...
Liker:  Successfully liked video
Liker:  Checking whether subscribed...
Liker:  We are subscribed
Liker:  Trying to like video...
Liker:  Video has already been auto-liked. User must have un-liked it, so we won't like it again
Liker:  Checking whether subscribed...
Liker:  We are subscribed
Liker:  Trying to like video...
Liker:  Video has already been auto-liked. User must have un-liked it, so we won't like it again
Liker:  Checking whether subscribed...
Liker:  We are subscribed
Liker:  Trying to like video...
Liker:  Video has already been auto-liked. User must have un-liked it, so we won't like it again
(...)`

**Comment by HatScripts** [comment]
@GroovyDrifter Thanks, fixed. v1.3.12 - https://github.com/HatScripts/youtube-auto-liker/commit/ea66a750ef71e4024c2ebcc6e3cefad2b81c1c2e

**Comment by NoahBK** [comment]
Instead v1.3.12 and still not working. I can attach a dubug log if I need to as @GroovyDrifter earlier if it helps you. Thank you for working on the script and fixing issues stopping it from working.

**Comment by HatScripts** [comment]
@NoahBK A debug log would be appreciated and helpful. Thanks.

**Comment by NoahBK** [comment]
@HatScripts No problem at all. Thank you for working to keep it updated!

> userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.02/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.03/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.06/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.09/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.11/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.14/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.17/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.20/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.22/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.27/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.33/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.38/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.44/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.49/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.55/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.60/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.66/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:958 YouTube Auto-Liker:  Waiting until watch threshold reached (0.71/0.75)...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:1005 YouTube Auto-Liker:  Trying to like video...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:1026 YouTube Auto-Liker:  Found like button
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:1030 YouTube Auto-Liker:  It's unclicked. Clicking it...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:1033 YouTube Auto-Liker:  Successfully liked video
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:1005 YouTube Auto-Liker:  Trying to like video...
userscript.html?name=YouTube%2520Auto-Liker.user.js&id=1019710a-0ee6-4007-94ee-db585e26c3a2:1023 YouTube Auto-Liker:  Video has already been auto-liked. User must have un-liked it, so we won't like it again

[This is the video I was watching if that helps](https://www.youtube.com/watch?v=5I0pUxSJ3iE)

And I have tried this with completely default settings. 75% watch duration/like if not subscribed (that's what I used when it worked for me) and combinations in-between. Nothing seems to make it work for me. It says that it is liking the video, but it doesn't.

**Comment by HatScripts** [comment]
@NoahBK Could you tell me the following information?
* Operating system (e.g. Windows 11 version 22H2)
* Browser (e.g. Firefox 106.0.1)
* Userscript manager (e.g. Tampermonkey 4.18.0)

**Comment by NoahBK** [comment]
@HatScripts For sure!

- Windows 10 version 21H2
- Brave version 1.44.112 (chromium version 106.0.5249.119)
- Tampermonkey version 4.18.0
- YouTube Auto-Liker version v1.3.16

**Comment by HatScripts** [comment]
@NoahBK Thanks. Could you please try again with the latest version [v1.3.19](https://github.com/HatScripts/youtube-auto-liker/raw/master/youtube-auto-liker.user.js)?

**Comment by NoahBK** [comment]
@HatScripts I have since updated to v1.3.19 and still no dice. Same issue as before. The script now continues to keep liking the video, but it never likes it. I appreciate you trying to fix the issue, but I also understand that it may just be something I have done differently or another extension interfering with it.
